name: Update Changelog
on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: get-default-branch
        run: |
          branch=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY" | jq -r '.default_branch')
          echo "default_branch=$branch" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.default_branch }}
      - name: update-changelog
        run: |
          MAJOR_VERSION=$(ls | grep CHANGELOG |  cut -d'-' -f 2 | cut -f 1 -d '.' |  grep v | sort -V -r | head -n 1)
          if [ -z "$MAJOR_VERSION" ]; then
            MAJOR_VERSION=0
          else
            MAJOR_VERSION=${MAJOR_VERSION#"v"}
            MAJOR_VERSION=$((MAJOR_VERSION+1))
          fi
          
          previous_tag=$(docker run -e MAJOR_VERSION=$MAJOR_VERSION --rm mcr.microsoft.com/azterraform:latest previousTag ${{ github.repository_owner }} ${{ github.event.repository.name }} $MAJOR_VERSION.0.0)
          if [ -z $previous_tag ]; then
            docker run --rm -v $(pwd):/src -w /src githubchangeloggenerator/github-changelog-generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }} --no-issues --no-compare-link
          else
            docker run --rm -v $(pwd):/src -w /src githubchangeloggenerator/github-changelog-generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }} --no-issues --no-compare-link --since-tag=$previous_tag
          fi
          sudo chmod -R ugo+rwX .
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Update changelog'
          branch: ${{ env.default_branch }}